/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CoursePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coursePage";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroSubheading?: string;
  heroCtaText?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  uspItems?: Array<{
    label?: string;
    icon?: "shield" | "calendar" | "location" | "certificate" | "people";
    _key: string;
  }>;
  aboutHeading?: string;
  aboutText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  courseCategoryHeading?: string;
  courseCategories?: Array<{
    coursePage?: CoursePageReference;
    tagline?: string;
    _key: string;
  }>;
  upcomingCoursesHeading?: string;
  upcomingCoursesSubtext?: string;
  contactHeading?: string;
  contactText?: string;
};

export type CoursePage = {
  _id: string;
  _type: "coursePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eduAdminCourseTemplateId?: number;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  targetGroup?: string;
  prerequisites?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactEmail?: string;
  contactPhone?: string;
  address?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CoursePageReference
  | HomePage
  | CoursePage
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0] {    heroHeading,    heroSubheading,    heroCtaText,    heroImage,    uspItems,    aboutHeading,    aboutText,    aboutImage { asset->, alt },    courseCategoryHeading,    courseCategories[] {      tagline,      eduAdminCourseTemplateId,      coursePage-> {        title,        slug,        eduAdminCourseTemplateId,        shortDescription      }    },    upcomingCoursesHeading,    upcomingCoursesSubtext,    contactHeading,    contactText,    layout[] { sectionType, visible }  }
export type HOME_PAGE_QUERY_RESULT = {
  heroHeading: string | null;
  heroSubheading: string | null;
  heroCtaText: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  uspItems: Array<{
    label?: string;
    icon?: "calendar" | "certificate" | "location" | "people" | "shield";
    _key: string;
  }> | null;
  aboutHeading: string | null;
  aboutText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  aboutImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    alt: string | null;
  } | null;
  courseCategoryHeading: string | null;
  courseCategories: Array<{
    tagline: string | null;
    eduAdminCourseTemplateId: null;
    coursePage: {
      title: string | null;
      slug: Slug | null;
      eduAdminCourseTemplateId: number | null;
      shortDescription: string | null;
    } | null;
  }> | null;
  upcomingCoursesHeading: string | null;
  upcomingCoursesSubtext: string | null;
  contactHeading: string | null;
  contactText: string | null;
  layout: null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: COURSE_PAGE_QUERY
// Query: *[_type == "coursePage" && slug.current == $slug][0] {    title,    slug,    eduAdminCourseTemplateId,    shortDescription,    description,    antalDagar,    omUtbildningen,    innehall,    upplagg,    upplaggText,    dagSchema[] {      dagTitel,      dagSubtitel,      pass[] {        tid,        typ,        aktiviteter      }    },    infoFlikar[] {      titel,      text,      highlightText    },    certifiering {      text,      highlightText    },    lodprov,    targetGroup,    prerequisites,    layout[] { sectionType, visible }  }
export type COURSE_PAGE_QUERY_RESULT = {
  title: string | null;
  slug: Slug | null;
  eduAdminCourseTemplateId: number | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  antalDagar: null;
  omUtbildningen: null;
  innehall: null;
  upplagg: null;
  upplaggText: null;
  dagSchema: null;
  infoFlikar: null;
  certifiering: null;
  lodprov: null;
  targetGroup: string | null;
  prerequisites: string | null;
  layout: null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_COURSE_SLUGS_QUERY
// Query: *[_type == "coursePage" && defined(slug.current)] {    "slug": slug.current  }
export type ALL_COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: COURSE_TEMPLATE_SLUG_MAP_QUERY
// Query: *[_type == "coursePage" && defined(slug.current) && defined(eduAdminCourseTemplateId)] {    eduAdminCourseTemplateId,    "slug": slug.current  }
export type COURSE_TEMPLATE_SLUG_MAP_QUERY_RESULT = Array<{
  eduAdminCourseTemplateId: number | null;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    title,    heroHeading,    heroText,    content  }
export type PAGE_QUERY_RESULT = null;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    contactEmail,    contactPhone,    address  }
export type SITE_SETTINGS_QUERY_RESULT = {
  contactEmail: string | null;
  contactPhone: string | null;
  address: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homePage"][0] {\n    heroHeading,\n    heroSubheading,\n    heroCtaText,\n    heroImage,\n    uspItems,\n    aboutHeading,\n    aboutText,\n    aboutImage { asset->, alt },\n    courseCategoryHeading,\n    courseCategories[] {\n      tagline,\n      eduAdminCourseTemplateId,\n      coursePage-> {\n        title,\n        slug,\n        eduAdminCourseTemplateId,\n        shortDescription\n      }\n    },\n    upcomingCoursesHeading,\n    upcomingCoursesSubtext,\n    contactHeading,\n    contactText,\n    layout[] { sectionType, visible }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "coursePage" && slug.current == $slug][0] {\n    title,\n    slug,\n    eduAdminCourseTemplateId,\n    shortDescription,\n    description,\n    antalDagar,\n    omUtbildningen,\n    innehall,\n    upplagg,\n    upplaggText,\n    dagSchema[] {\n      dagTitel,\n      dagSubtitel,\n      pass[] {\n        tid,\n        typ,\n        aktiviteter\n      }\n    },\n    infoFlikar[] {\n      titel,\n      text,\n      highlightText\n    },\n    certifiering {\n      text,\n      highlightText\n    },\n    lodprov,\n    targetGroup,\n    prerequisites,\n    layout[] { sectionType, visible }\n  }\n': COURSE_PAGE_QUERY_RESULT;
    '\n  *[_type == "coursePage" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': ALL_COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "coursePage" && defined(slug.current) && defined(eduAdminCourseTemplateId)] {\n    eduAdminCourseTemplateId,\n    "slug": slug.current\n  }\n': COURSE_TEMPLATE_SLUG_MAP_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    title,\n    heroHeading,\n    heroText,\n    content\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    contactEmail,\n    contactPhone,\n    address\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
